const fakeData=[
    {
        id: 1,
        name: "Healthy Meal Plan",
        description: "How we dream about our future",
        price : 23.99,
        image : '../../../hot-onion-restaurent-resources-master/lunch/lunch1.png',
        category:"lunch",
    },
    {
        id: 2,
        name: "Fried Chicken Bento",
        description: "How we dream about our future",
        price : 9.99,
        image : '../../../hot-onion-restaurent-resources-master/lunch/lunch2.png',
        category:"lunch",
    },
    {
        id: 3,
        name: "Tarragon-Rubbed-Salmon",
        description: "How we dream about our future",
        price : 6.99,
        image : '../../../hot-onion-restaurent-resources-master/lunch/lunch3.png',
        category:"lunch",
    },
    {
        id: 4,
        name: "Indian Lunch",
        description: "How we dream about our future",
        price : 8.99,
        image : '../../../hot-onion-restaurent-resources-master/lunch/lunch4.png',
        category:"lunch",
    },
    {
        id: 5,
        name: "Beef Steak",
        description: "How we dream about our future",
        price : 15.99,
        image : '../../../hot-onion-restaurent-resources-master/lunch/lunch5.png',
        category:"lunch",
    },
    {
        id: 6,
        name: "Honey-Soy-Glazed Salmon with Peppers",
        description: "How we dream about our future",
        price : 7.99,
        image : '../../../hot-onion-restaurent-resources-master/lunch/lunch6.png',
        category:"lunch",
    },
    {
        id: 7,
        name: "Bagel and cream cheese",
        description: "How we dream about our future",
        price : 6.99,
        image : '../../../hot-onion-restaurent-resources-master/Breakfast/breakfast1.png',
        category:"breakfast",
    },
    {
        id: 8,
        name: "Breakfast sandwich",
        description: "How we dream about our future",
        price : 9.99,
        image : '../../../hot-onion-restaurent-resources-master/Breakfast/breakfast2.png',
        category:"breakfast",
    },
    {
        id: 9,
        name: "Baked Chiken",
        description: "How we dream about our future",
        price : 10.99,
        image : '../../../hot-onion-restaurent-resources-master/Breakfast/breakfast3.png',
        category:"breakfast",
    },
    {
        id: 10,
        name: "Eggs Benedict",
        description: "How we dream about our future",
        price : 8.99,
        image : '../../../hot-onion-restaurent-resources-master/Breakfast/breakfast4.png',
        category:"breakfast",
    },
    {
        id: 11,
        name: "Toast Croissant Fried egg",
        description: "How we dream about our future",
        price : 19.99,
        image : '../../../hot-onion-restaurent-resources-master/Breakfast/breakfast5.png',
        category:"breakfast",
    },
    {
        id: 12,
        name: "Full Breakfast Fried Egg Toast Brunch",
        description: "How we dream about our future",
        price : 3.99,
        image : '../../../hot-onion-restaurent-resources-master/Breakfast/breakfast6.png',
        category:"breakfast",
    },
    {
        id: 13,
        name: "Salmon with Grapefruit and lentil salad",
        description: "How we dream about our future",
        price : 9.99,
        image : '../../../hot-onion-restaurent-resources-master/Dinner/dinner1.png',
        category:"dinner",
    },
    {
        id: 14,
        name: "Lemony Sakmon Piccata",
        description: "How we dream about our future",
        price : 10.99,
        image : '../../../hot-onion-restaurent-resources-master/Dinner/dinner2.png',
        category:"dinner",
    },
    {
        id: 15,
        name: "Park Tenderloin With Quinoa Pilaf",
        description: "How we dream about our future",
        price : 12.99,
        image : '../../../hot-onion-restaurent-resources-master/Dinner/dinner3.png',
        category:"dinner",
    },
    {
        id: 16,
        name: "French fries with cheese",
        description: "How we dream about our future",
        price : 8.99,
        image : '../../../hot-onion-restaurent-resources-master/Dinner/dinner4.png',
        category:"dinner",
    },
    {
        id: 17,
        name: "Garlic Butter Baked Salmon",
        description: "How we dream about our future",
        price : 6.99,
        image : '../../../hot-onion-restaurent-resources-master/Dinner/dinner5.png',
        category:"dinner",
    },
    {
        id: 18,
        name: "Baked Chiken",
        description: "How we dream about our future",
        price : 9.99,
        image : '../../../hot-onion-restaurent-resources-master/Dinner/dinner6.png',
        category:"dinner",
    },

]
export default fakeData;